config:
   setoresParenes: [
      "utilidade-publica",
      "materiais-basicos",
      "financeiro-e-outros",
      "saude"]
   minimoFreeFloat: 25.00
   minimoROE: 10.00
   minimoCagrLucro5anos: 15.00
   minimoMargemLiquida: 10.00
   minimoLiquidez: 1
   maximoDividaLiquidaSobrePatrimonioLiquido: 2.00
   maximoDividaLiquidaSobreEbitda: 2.50
   maximoPrecoSobreLucro: 15.00
   maximoPrecoSobreValorPatrimonial: 3.00

   databaseName: ${DATABASE_NAME}
   urlDatabase: ${URL_DATABASE}
   timeoutDatabase: 60000

   urlExternalAPI: ${URL_EXTERNAL_API}
   timeoutExternalAPI: 60000
   timeMinRetry: 2000
   timeMaxRetry: 5000
   maxAttempsRetry: 3

   messageTickerNotFound: "Sorry, the ticker not found!"
   messageConnectionFail: "Sorry, the connection whith external API is fail. Retry again after 1 minute!"

server:
   port: 8888

logging:
   level:
      ROOT: INFO

