config:
   minimoFreeFloat: 25.00
   minimoROE: 10.00
   minimoCagrLucro5anos: 15.00
   minimoMargemLiquida: 10.00
   minimoLiquidez: 2.00
   maximoDividaLiquidaSobrePatrimonioLiquido: 2.00
   maximoDividaLiquidaSobreEbitda: 2.50
   maximoPrecoSobreLucro: 15.00
   maximoPrecoSobreValorPatrimonial: 3.00

   url: "<URL_API>"
   timeout: 1

server:
   port: 8888